apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-landing
spec:
  replicas: 1
  template:
    metadata:
      name: web-server-landing
      labels:
        app: web-server-landing
    spec:
      containers:
      - name: main
        image: dummyai/web-server-landing
        command: 
        - npm 
        - run
        - start:browser-dev
        ports:
        - containerPort: 3000
        tty: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-web-server-landing
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: "dummy-ingress"
spec:
  rules:
  - http:
      paths:
      - path: /landing
        backend:
          serviceName: web-server-landing
          servicePort: 3000
  backend:
    serviceName: default-http-backend
    servicePort: 80
