apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  template:
    metadata:
      name: web-server
      labels:
        app: web-server
    spec:
      containers:
      - name: main
        image: dummyai/web-server
        command: 
        - npm 
        - run
        - start:browser-dev
        ports:
        - containerPort: 3000
        tty: true

