# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  pip-install-moxel-python2:
    docker:
      - image: python:2
    steps:
      - run: pip install moxel
      - run: moxel version
  pip-install-moxel-python3:
    docker:
      - image: python:3
    steps:
      - run: pip install moxel
      - run: moxel version

workflows:
  version: 2
  build_and_test:
    jobs:
        - pip-install-moxel-python2
        - pip-install-moxel-python3
