# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  pip-install-moxel-python2:
    docker:
      - image: python:2
    steps:
      - run: pip install moxel
      - run: moxel version
  pip-install-moxel-python3:
    docker:
      - image: python:3
    steps:
      - run: pip install moxel
      - run: moxel version
  ci-perceptron: 
    docker:
        - image: python:3
    steps:
        - run: git clone https://github.com/moxel/perceptron
        - run: pip install moxel pexpect
        - run: cd perceptron && git checkout -b ci-perceptron && git pull origin ci-perceptron && python test_push.py && python test_client.py
        - run: ENV=dev moxel teardown ci-perceptron:latest
  ci-perceptron-dir: 
    docker:
        - image: python:3
    steps:
        - run: git clone https://github.com/moxel/perceptron
        - run: pip install moxel pexpect
        - run: cd perceptron && git checkout -b ci-perceptron-dir && git pull origin ci-perceptron-dir && python test_push.py && python test_client.py
        - run: ENV=dev moxel teardown ci-perceptrond-dir:latest

workflows:
  version: 2
  build_and_test:
    jobs:
        - pip-install-moxel-python2
        - pip-install-moxel-python3
        - ci-perceptron
        - ci-perceptron-dir
