apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master-server
spec:
  replicas: 1
  template:
    metadata:
      name: master-server
      labels:
        app: master-server
    spec:
      containers:
      - name: main
        image: dummyai/master-server
        env:
        - name: ENV
          value: dev
        command: 
        - /app/master-server
        - start
        volumeMounts:
        - name: nfs
          mountPath: "/mnt/nfs"
        ports:
        - containerPort: 8080
        tty: true
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-master-server
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: "dummy-ingress"
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: master-server
          servicePort: 8080
  backend:
    serviceName: default-http-backend
    servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-git
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "dummy-ingress"
    ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
  - http:
      paths:
      - path: /git
        backend:
          serviceName: master-server
          servicePort: 8080
  backend:
    serviceName: default-http-backend
    servicePort: 80
