apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: releaser
spec:
  replicas: 2
  template:
    metadata:
      name: releaser
      labels:
        app: releaser
    spec:
      containers:
      - name: main
        image: dummyai/releaser
        ports:
        - containerPort: 8080
        tty: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-releaser
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: "dummy-ingress"
spec:
  rules:
  - http:
      paths:
      - path: /release
        backend:
          serviceName: releaser
          servicePort: 8080
  backend:
    serviceName: default-http-backend
    servicePort: 80
