site_name: Warpdrive
theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
pages:
- Warpdrive:
  - 'warpdrive/install.md'
  - 'warpdrive/proposal.md'
- Tutorial:
  - 'tensorflow-object-detection.md'
  - 'caffe-colorization.md'
