site_name: Moxel
theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
pages:
- index.md
- Moxel:
  - 'moxel/install.md'
- Tutorial:
  - 'tutorials/caffe-colorization.md'
