site_name: Warpdrive
theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
pages:
- 'index.md'
- Deployment:
  - 'tensorflow-object-detection.md'
  - 'caffe-colorization.md'
